include: package:lints/recommended.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
  errors:
    omit_local_variable_types: ignore
    annotate_overrides: ignore
    use_function_type_syntax_for_parameters: ignore
    missing_required_param: warning
    missing_return: warning
    prefer_single_quotes: warning

linter:
  rules:
    constant_identifier_names: false
    file_names: false